FROM pytorch/pytorch:1.10.0-cuda11.3-cudnn8-runtime AS base

ARG DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"

RUN apt-get update && \
    apt-get install --yes software-properties-common && \
    apt-get install --yes \
    python3-pip \
    python3-opencv \
    python3-tqdm \
    python3-pil \
    screen \
    zip \
    vim \
    git \
    wget \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-py39_24.1.2-0-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-py39_24.1.2-0-Linux-x86_64.sh -b \
    && rm -f Miniconda3-py39_24.1.2-0-Linux-x86_64.sh

COPY . /src
WORKDIR /src
#RUN conda install -y -f /src/requirements.txt
RUN conda install -y pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 -c pytorch
RUN conda install -y pandas scikit-learn matplotlib numpy
RUN conda install -y jupyter notebook scipy=1.5.2

#RUN pip3 install -r /src/requirements.txt
#RUN pip3 install pandas

CMD ["/bin/bash"]
